---
delegatebot:
  watch:
  - target: { channel: &cli C032824SM }
  - target: { channel: &cli-dev-internal CDVP0651P }
  - target: { channel: &v3-acceleration-team CCRLX88DD }
  delegate: &interrupts
    if:
      when:
        - hours: { tz: America/Los_Angeles, start: 09:00, end: 18:00 }
        - day: { tz: America/Los_Angeles, days: [ Mon, Tue, Wed, Thu, Fri ] }
        - not: { date: { tz: America/Los_Angeles, dates: [ 2019-01-01, 2019-01-21, 2019-02-18, 2019-05-27, 2019-07-04, 2019-09-02, 2019-11-28, 2019-11-29, 2019-12-25 ] } }
      then:
        literalmap:
          from:
            pairist:
              team: cli
              role: interrupt
          users:
            Alexander: UCLGW13UZ
            James: UENAH6TE3
            Jenna: UMZ7PEESC
            Nick: UV5NRP803
            Sebastian: U6WBMK9QW
            Steve: U0W3640SW
            
  options:
    empty_message: Sorry, no interrupt is available right now. The community may be able to help, or feel free to ping again later.

